spring:
   mvc:
      view:
        prefix: WEB-INF/jsp/
        suffix: .jsp
   datasource:
     url: jdbc:mysql://127.0.0.1:3306/c71-s3-plr-zufang
     username: root
     password: a
     driver-class-name: com.mysql.jdbc.Driver
#sprinBoot实现自动化配置
#两个入口 1.pom.xml springboot的配置文件 application*.yaml
#        2.SpringBoot启动类
#            @SpringBootApplication注释的组成
#                 @SpringBootConfiguration SpringIOC配置注释==》beans.xml
#                 @ComponentScan 主键扫描注解 =》会自动扫描启动类所在包以及子包
#
#                 @EnableAutoConfiguration  
 #                     @AutoConfigurationPackage 自动配置包
 #                     @Import(AutoConfigurationImportSelector.class) 导入启动选择器
#                
#
#